services:

  mongo:
    image: mongo
    restart: always
    networks:
      - default
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

  backend-howlongtobeatmybacklog:
    image: acim/go-reflex
    environment:
      - RACE_DETECTOR=1
    volumes:
      - .:/app
    ports:
      - 8080:8080
    depends_on:
      - mongo

volumes:
  mongodb:
  mongodb_config: